### ISSUE TITLE
Баг при использовании команды branch в определении colon слова

### ISSUE THREAD

**Issue by yurijvolkov** [Firemoon777/forth-interpreter#2]
При выполнении следующего кода получим Segmentation fault:

> : skip branch 2 ;
> : t skip + + \* ;
> 1
> 2
> 3
> 4
> t
> Segmentation fault

**Comment by yurijvolkov** [comment]
Этот баг можно списать на непродуманность архитектуры команды branch, но всё же проблема актуальна при попытке создать команды типа skip.

**Comment by Firemoon777** [comment]
Ну... Интерпретатор далёк от совершенства, да. Однако, указанное тобой -- скорее неправильное использование слова branch, а не баг.

**Comment by yurijvolkov** [comment]
Ну вопрос неоднозначный. И я склоняюсь к тому что использование верное. Ведь если добавить к команде ветвления (в данном случае branch) параметр, принимающий глубину перехода N. И потом инкрементить не PC, а N-ое число с вершины стека, получится реализовать переходы в языке с любой глубиной вызова функций.

**Comment by oshnix** [comment]
В данном случае можно руководствоваться реализацией gforth. На этом примере она также выдаёт ошибку доступа к памяти
